"""Regenerate recompiled C++ and sync only changed files into generated/ (keeps rebuilds incremental).

Steps: merge SCE library bindings from ps2_analyzer and missed function starts from find_code_pointers.py into the
config (work/killzone.merged.toml), run ps2_recomp into work/gen_tmp, then copy changed/new files to generated/ and
delete stale ones.
Usage: python tools/scripts/regen.py
"""
import filecmp, os, re, shutil, subprocess, sys, tomllib

# Killzone ships the register-locals code generator (patch 0017); PS2X_CODEGEN=classic regenerates the old style.
os.environ.setdefault('PS2X_CODEGEN', 'locals')
# Guest control flow without the scheduler (patch 0023): tail jumps followed by the caller (ps2_cg_dsp.h) and the entry_*
# fragments folded into their functions. PS2X_CODEGEN_DSP=0 / PS2X_CODEGEN_FOLD=0 give the patch-0017 output.
os.environ.setdefault('PS2X_CODEGEN_DSP', '1')
os.environ.setdefault('PS2X_CODEGEN_FOLD', '1')
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CFG = ROOT / "config" / "killzone.toml"
ANALYZER_TOML = ROOT / "work" / "analyzer.toml"
# KZ_GEN_DIR / KZ_GEN_TMP / KZ_MERGED / KZ_RECOMP_EXE redirect the run (used for alternative code generators, e.g.
# PS2X_CODEGEN=locals into work/generated_cg) without touching generated/.
MERGED = Path(os.environ.get("KZ_MERGED", ROOT / "work" / "killzone.merged.toml"))
TMP = Path(os.environ.get("KZ_GEN_TMP", ROOT / "work" / "gen_tmp"))
GEN = Path(os.environ.get("KZ_GEN_DIR", ROOT / "generated"))
RECOMP = Path(os.environ.get("KZ_RECOMP_EXE", ROOT / "build" / "ps2recomp" / "ps2xRecomp" / "ps2_recomp.exe"))
ANALYZER = ROOT / "build" / "ps2recomp" / "ps2xAnalyzer" / "ps2_analyzer.exe"


def merged_config() -> str:
    text = CFG.read_text()
    if not ANALYZER_TOML.exists():
        subprocess.run([str(ANALYZER), str(ROOT / "game" / "SCUS_974.02"), str(ANALYZER_TOML)],
                       check=True, stdout=subprocess.DEVNULL)
    have = {s.split("@")[1].upper() for s in tomllib.loads(text)["general"]["stubs"] if "@" in s}
    extra = [s for s in tomllib.loads(ANALYZER_TOML.read_text())["general"].get("stubs", [])
             if "@" in s and s.split("@")[1].upper() not in have]
    lines = "".join(f'  "{s}",\n' for s in extra)
    text = re.sub(r"(stubs = \[\n)", lambda m: m.group(1) + lines, text, count=1)
    text = re.sub(r'^output = .*$', f'output = "{TMP.as_posix()}"', text, count=1, flags=re.M)
    print(f"[regen] +{len(extra)} SCE library bindings from ps2_analyzer")
    subprocess.run([sys.executable, str(ROOT / "tools" / "scripts" / "find_code_pointers.py")], check=True)
    entries = [l.strip() for l in (ROOT / "work" / "code_pointers.txt").read_text().splitlines() if l.strip()]
    entry_line = "entry_points = [" + ", ".join(f'"{e}"' for e in entries) + "]\n"
    text = re.sub(r"(\[general\]\n)", lambda m: m.group(1) + entry_line, text, count=1)
    print(f"[regen] +{len(entries)} entry points from find_code_pointers")
    return text


def sync() -> None:
    GEN.mkdir(exist_ok=True)
    new = {p.name for p in TMP.iterdir()}
    changed = 0
    for name in new:
        src, dst = TMP / name, GEN / name
        if not dst.exists() or not filecmp.cmp(src, dst, shallow=False):
            shutil.copy2(src, dst)
            changed += 1
    stale = [p for p in GEN.iterdir() if p.name not in new]
    for p in stale:
        p.unlink()
    print(f"[regen] {len(new)} files: {changed} changed/new, {len(stale)} removed")


def main() -> int:
    MERGED.write_text(merged_config())
    if TMP.exists():
        shutil.rmtree(TMP)
    log = Path(os.environ.get("KZ_RECOMP_LOG", ROOT / "work" / "recomp.log"))
    with log.open("w") as f:
        r = subprocess.run([str(RECOMP), str(MERGED)], stdout=f, stderr=subprocess.STDOUT)
    if r.returncode != 0:
        print(f"[regen] ps2_recomp failed ({r.returncode}); see {log}")
        return r.returncode
    reject_data_candidates(log)
    sync()
    return 0


def reject_data_candidates(log: Path) -> None:
    """Record added entry points whose bodies failed to decode (data embedded in .text) so the next regen skips them."""
    cands = {int(l, 16) for l in (ROOT / "work" / "code_pointers.txt").read_text().split()}
    bad = set()
    for line in log.read_text(errors="replace").splitlines():
        m = re.search(r"\[error\] unhandled-instruction function=entry_([0-9a-f]+) ", line)
        if m and int(m.group(1), 16) in cands:
            bad.add(int(m.group(1), 16))
    reject = ROOT / "config" / "code_pointers_reject.txt"
    old = reject.read_text().splitlines() if reject.exists() else ["# data mistaken for code; generated by regen.py"]
    have = {l.split()[0].lower() for l in old if l.strip() and not l.startswith("#")}
    new = [f"0x{v:08X}" for v in sorted(bad) if f"0x{v:08x}" not in have]
    if new:
        reject.write_text("\n".join(old + new) + "\n")
        print(f"[regen] {len(new)} entry points rejected as data (take effect next regen)")


if __name__ == "__main__":
    sys.exit(main())
